name: Build dashboard
env:
  ANDROID_BETA_URL: "https://dl.google.com/developers/android/baklava/images/factory/oriole_beta-bp31.250610.009-factory-55b4d2fb.zip"
on:
  workflow_dispatch:
  schedule:
    # Every Monday at 12am
    - cron: "0 0 * * 1"
jobs:
  gen_report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fonttools requests PyGithub
      - name: Grab and mount android fonts
        run: |
          wget $ANDROID_BETA_URL --quiet -O android.zip
          mkdir android
          unzip -j android.zip -d android
          unzip -j android/image*zip -d android
          mkdir -p android/system
          test -f android/system.img || (echo "system.img not found!" && exit 1)
          sudo mount -o loop,ro -t ext4 android/system.img android/system || sudo dmesg | tail -20
      - name: Checkout notofonts
        uses: actions/checkout@v3
        with:
          repository: notofonts/notofonts.github.io
          path: notofonts.github.io
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Generate report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
      - name: Upload build artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist
  deploy:
    needs: gen_report
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
